### ISSUE TITLE
Establish a verification checklist

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#198]
@meissadia @shindigira @billhimmelsbach 

I would like to establish a verification checklist for our components so that we can share in the responsibilities of reviewing and verifying. Please review provide feedback or additions. 

### Verify the CFPB Design System (React) component against the CFPB Design System
- [ ] Has component intro text copied from the DS page
- [ ] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [ ] Each DS variant is implemented as a separate story
  - [ ] Story name should be sentence case (ex. List Link => List link)
  - [ ] Naming is consistent with the DS
  - [ ] Same component names, same placeholder text, etc.
- [ ] Order of stories matches between DS/DSR
- [ ] Component is built correctly
  - [ ] Visually compare DSR implementation to DS
  - [ ] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [ ] Manual visual review has been conducted and component has passed this review

#### For new components 
- [ ] All steps for existing components plus the following steps
- [ ] The new component has been added to the CFPB Design System OR
- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system
- [ ] Documentation has been written for the new component (this is not a blocker for moving a component to verified)

### Run accessibility checks 
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [ ] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [ ] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, the CFPB design system, WebAIM, or similar accessibility examples?
- [ ] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [ ] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

**Comment by meissadia** [comment]
@natalia-fitzgerald Looks great!
 
- `The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB web app (is this a necessary step or is it enough that it's in Storybook?)`

  I think Storybook is a standalone space where we can verify that components work.  Stories should be implemented in a way that reviewers can validate functionality, accessibility, 

- `Visual regression testing has been conducted`
  I don't yet know enough about how to use Chromatic (and I think the integration is broken again), so I would vote to skip this for now.

**Comment by billhimmelsbach** [comment]
This is looking great @natalia-fitzgerald!

> * [ ]  The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB web app (is this a necessary step or is it enough that it's in Storybook?)

I have mixed feelings if the component needs to be used before it can be validated? When I've integrated new components from component libraries, I often do have to make small tweaks, but I don't think that should prevent it from being validated?

> * [ ]  Component is screen reader friendly

How have people been verifying this so far? I usually use VoiceOver on my mac, but I've seen significant differences when testing things out in JAWS or Narrator on windows at previous gigs.

It wouldn't have to be part of this more high level definition of done document, but it might be worth breaking this task down into smaller tasks when we do our code reviews (Verify that meaningful visible text is conveyed, links have descriptive text, etc.). Maybe just by linking to a generic accessibility checklist that includes a screen reader section [like this one ](https://spotlight.duke.edu/communications/wp-content/uploads/sites/25/2017/11/Accessibility-Testing-Checklist3.pdf) or just the WCAG docs?

> **For new components:**

Could we add something about testing coverage here to this section? I saw in [sbl-project's definition of done](https://github.com/cfpb/sbl-project#definition-of-done) a generic >85% code coverage requirement, which while an arbitrary benchmark, might be nice to have here.

Thanks Natalia!

**Comment by natalia-fitzgerald** [comment]
Thanks for your feedback @billhimmelsbach @meissadia 
- I'll remove this item: "The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB web app" but we should capture somewhere that there could be changes when a component is finally used in the _real world_. I see this as a test of the component. 
- For accessibility checks let's follow the [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) and [Lighthouse automated audit] (https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#lighthouse-automated-audit-1)
- At what phase of the process would we like to run the accessibility audit? Component level? Page level? If we wait for the page level we should make a short list of quick things to check at the component phase.
- @billhimmelsbach Can you elaborate on the code coverage benchmark? Or do other devs have thoughts on that? 
- I'll remove the visual regression testing but if we are doing manual visual review instead I'd like to be sure we are working from the CFPB Design System component and styles as much as possible unless there is a justification for deviating. When there are changes we wish to make we should push them to the CFPB Design System and have them feed back out to the DSR.

**Comment by billhimmelsbach** [comment]
> I don't yet know enough about how to use Chromatic (and I think the integration is broken again), so I would vote to skip this for now.

I haven't used Chromatic much either @meissadia, but I put up a [PR this morning](https://github.com/cfpb/design-system-react/pull/199) to hopefully at least get the integration working again. 🤞 I have used other visual regression tooling, so might be worth fixing up once our components are more stable.

**Comment by meissadia** [comment]
Verifying DSR component
- [ ] Has component intro text copied from the DS page
- [ ] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [ ] Each DS variant is implemented as a separate story
  - [ ] Story name should be sentence case (ex. List Link => List link)
  - [ ] Naming is consistent with DS
    - [ ] Same component names, same placeholder text, etc.
- [ ] Order of stories matches between DS/DSR
- [ ] Component is built correctly
  - [ ] Visually compare DSR implementation to DS
  - [ ] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
  - [ ] Verify component unit tests are implemented and passing (ex: `yarn vitest Button`)

**Comment by natalia-fitzgerald** [comment]
We are closing this one out since we are using the checklist.
