### ISSUE TITLE
Page-by-page: Shared Platform Components for CFPB Design System (in React) 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#224]
This issue will be used to capture the work that our team is doing related to building out components for CFPB Design System (in React) (we'll refer to it as DSR from here on out to be concise and to more easily differentiate from the CFPB Design System).

Our current work is tied to the components needed for the Shared platform (authentication and authorization). When we move on to the SBL app I will create an issue to track those components. 

#### This work includes:
- [ ] Verify components that have already been built as "Draft" in the DSR
- [ ] Bring existing CFPB Design System components to the DSR
- [x] Establish a process for [verification of CFPB Design System components](https://github.com/cfpb/design-system-react/issues/198) of DSR components
- [ ] Set up a process for designing and developing new components (components that are not in the CFPB Design System)

Contribution onboarding: https://github.com/cfpb/design-system-react/issues/232

**Comment by natalia-fitzgerald** [comment]
## Page: Confirm user profile details
Checkmark means the component exists in the DSR has been verified. 

**Needs to be verified:**
- [ ] Global eyebrow @billhimmelsbach https://github.com/cfpb/design-system-react/issues/213
-   [ ] Tagline 
- [ ] consumerfinance.gov header 
- [x] Text introduction
  - [x] Lead paragraph
  - [x] Paragraph
  - [ ] Links (@billhimmelsbach #49)
- [x] Heading 2
- [x] Paragraph/Body
- [ ] Well (@billhimmelsbach  #45)
- [ ] Label 
- [ ] Text input
- [ ] Error notification (field-level)
- [ ] Error notification (page level)
- [ ] Helper text
- [ ] Select (Spike @meissadia https://github.com/cfpb/design-system-react/issues/197)
   - [ ] Single select 
   - [ ] Multiselect - Spike 
      - [ ] With checkboxes
      - [ ] With tags (pills)
- [x] Tags redesign - @meissadia  https://github.com/cfpb/design-system/issues/1760
- [x] Checkbox
   - [x] Checkbox option 
   - [x] Checkbox helper text
- [x] Button
- [ ] Button + Destructive link
- [ ] cf.gov footer

**Comment by natalia-fitzgerald** [comment]
## Page: Shared filing platform (unauthenticated)
Checkmark means the component exists in the DSR has been verified. 

**Needs to be verified:**
- [ ] Global eyebrow 
-   [ ] Tagline 
- [ ] Megamenu
- [ ] Hero
- [ ] Icons
  - [ ] Indent to account for icon list?
- [ ] Heading 3
- [ ] Paragraph

- [ ] Buttons
- [ ] Links
- [ ] Well
- [ ] cf.gov footer

Needs to be added to DSR: 
- [ ] Sidebar
- [ ] Related links
- [ ] Email sign-up

Remaining design details may require the following components: 
- [ ] Summary

**Comment by natalia-fitzgerald** [comment]
## Page: View financial institution details
Checkmark means the component exists in the DSR and has been verified. 

**Needs to be verified:**
- [ ] Global eyebrow 
  - [ ] Tagline 
**Needs to be verified:**
- [ ] Global eyebrow @billhimmelsbach https://github.com/cfpb/design-system-react/issues/213
-   [ ] Tagline 
- [ ] Modified header for Shared data filing platform?
- [x] Text introduction
  - [x] Lead paragraph
  - [x] Paragraph
  - [ ] Links
- [x] Heading 2
- [x] Paragraph
- [ ] Well
- [ ] Label 
- [x] Paragraph
- [ ] Table
- [ ] Pagination
- [ ] cf.gov footer

**Comment by natalia-fitzgerald** [comment]
## Page: Shared filing platform (unauthenticated)
Checkmark means the component exists in the DSR has been verified. 

### Required components
- [ ] Global eyebrow 
- [x] Tagline 
- [ ] Megamenu
- [ ] Hero
- [ ] Icons
  - [ ] Indent to account for icon list?
- [x] Heading 3
- [x] Paragraph
- [x] Buttons
- [x] Links
- [ ] Well
- [ ] cf.gov footer

Needs to be added to DSR: 
- [ ] Sidebar
- [ ] Related links
- [ ] ~~Email sign-up~~ 

Remaining design details may require the following component(s): 
- [ ] Summary

**Comment by natalia-fitzgerald** [comment]
## Page: Confirm user profile details
Checkmark means the component exists in the DSR has been verified. 

**Needs to be verified:**
- [ ] Global eyebrow @billhimmelsbach https://github.com/cfpb/design-system-react/issues/213
-   [x] Tagline @billhimmelsbach #218)
- [ ] consumerfinance.gov header 
- [x] Text introduction (@meissadia #193 )
  - [x] Lead paragraph (@meissadia #193 )
  - [x] Paragraph (@meissadia #193 )
  - [x] Links (@meissadia #215)
- [x] Heading 2
- [x] Paragraph/Body (@meissadia #162)
- [ ] Well (@billhimmelsbach  #45)
- [x] Label (@shindigira)
- [ ] **Text input** (@shindigira)
  - [ ] Include error states using [Notification](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-notifications--overview#warning--field-level-?%22)
- [ ] [Alerts](https://cfpb.github.io/design-system/components/alerts) 
- [ ] Error notification (page level)
- [ ] Helper text (@billhimmelsbach)
- [ ] Select (@meissadia #197)
   - [x] Single select 
   - [ ] Multiselect - Spike (#206 )
      - [x] With checkboxes
      - [x] With tags (pills)
      - [ ] Include error states using [Notification](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-notifications--overview#warning--field-level-?%22)
- [x] Multiselect Tag redesign - (@meissadia [DS #1760](https://github.com/cfpb/design-system/issues/1760))
- [x] Checkbox (@meissadia - [DSR Checkbox](https://cfpb.github.io/design-system-react/?path=/docs/components-verified-checkboxes--overview))
   - [x] Checkbox option 
   - [x] Checkbox helper text
- [x] Button (@meissadia) - [DSR Button](https://cfpb.github.io/design-system-react/?path=/docs/components-verified-buttons--overview)
- [x] Button + Destructive link (@billhimmelsbach)
- [ ] **cf.gov footer**

**Comment by natalia-fitzgerald** [comment]
## Page: Shared platform (authenticated)
Checkmark means the component exists in the DSR has been verified. 

**Needs to be verified:**
- [ ] Global eyebrow @

**Comment by natalia-fitzgerald** [comment]
## Page: Request changes to your user profile (read-only)
Checkmark means the component exists in the DSR has been verified. 

**Needs to be verified:**
- [ ] Component

**Comment by natalia-fitzgerald** [comment]
## Page: View financial institution details (read-only)
Checkmark means the component exists in the DSR and has been verified. 

### Required components
- [ ] Global eyebrow 
- [x] Tagline 
- [x] Text introduction
  - [x] Lead paragraph
  - [x] Paragraph
  - [x] Links
- [x] Heading 2
- [x] Paragraph
- [ ] Well
- [ ] Label 
- [x] Paragraph
- [ ] Table - @billhimmelsbach #46 
- [ ] Pagination
- [ ] cf.gov footer

**May need customization**
- [ ] Icon with text
  - Not currently a component, just a demo of putting an Icon next to text.
  - [Exploration of how to consistently space Icon + text](https://github.com/cfpb/design-system-react/issues/130)
    - "Your LEI status must be active..."

**Needs UI/UX design and thinking** 
These items are not a priority for this sprint. 
- [ ] SBL app page navigation 
- [ ] Modified header for Shared data filing platform?

**Comment by natalia-fitzgerald** [comment]
## Page: Small business lending home 
Checkmark means the component exists in the DSR and has been verified.

### Required components
- [ ] Component

**Comment by natalia-fitzgerald** [comment]
Here's a list of the current state of component things. Once again this list is focused on the shared platform and not the filing app. 

## As of 11/30
### Components (verified)
- Banner (US gov)
- Buttons
- Checkboxes
- Headings
- Labels
- Links
- Pagination
- Paragraphs
- Radio buttons
- Tables
- Taglines
- Text introductions
- Wells

### Components (Draft)
- Divider
- Dropdowns (should be removed)
- Expandable
- Footers
- Grids
- Heroes
- Icons
- Layout
- Lists
- Navbar
- Page header 
- Text inputs
- Select/Multiselect (needs to be pushed - DS blocker removed?)

### Needs to be added
- Megamenu? 
- Sidebar
- Related links
