### ISSUE TITLE
Verify and build components needed for current pages 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#230]
## Component parts
List of Design System (React) components that appear on pages that are currently in development. Checkmark means the component exists in the component library and is verified. 

**Needs to be verified:**
- [ ] us.gov banner (tagline or usa-banner) @billhimmelsbach https://github.com/cfpb/design-system-react/issues/213
- [ ] cf.gov header 
- [ ] Divider
- [ ] Well - @billhimmelsbach  #45 
- [ ] Helper text 
- [ ] Links - @billhimmelsbach #49 
- [ ] Table - @billhimmelsbach #46 
- [ ] cf.gov footer
- [ ] pagination  
- [ ] cf.gov footer
- [ ] Heroes

Check Sigmund's branch: 
- [ ] Label 
- [ ] Text input
- [ ] Error notification (field-level)
- [ ] Error notification (page level)

Not a component: 
- [ ] Icon with Text
  - Not currently a component, just a demo of putting an Icon next to text.
  - [Exploration of how to consistently space Icon + text](https://github.com/cfpb/design-system-react/issues/130)

**Needs to be built: **
- [x] Text introduction @meissadia https://github.com/cfpb/design-system-react/issues/158
    - [x] Heading 1
    - [x] Lead paragraph https://github.com/cfpb/design-system-react/issues/157
    - [x] Paragraph https://github.com/cfpb/design-system-react/issues/162
- [ ] Select (Spike @meissadia https://github.com/cfpb/design-system-react/issues/197)
   - [ ] Single select 
   - [ ] Multiselect - Spike 
      - [ ] With checkboxes
      - [ ] With tags (pills)
   - [ ] Tags redesign - @meissadia  https://github.com/cfpb/design-system/issues/1760

**Verified** 
- [x] Headings
- [x] Checkbox
    - [x] Checkbox option 
    - [x] Checkbox helper text
- [x] Button

**May need customization**  
- Icon with text
  - "Your LEI status must be active..."

**Needs UI/UX design**
These items are not a priority for this sprint. 
- [ ] SBL app page navigation 

**Additional components**
- [ ] Sidebar
- [ ] Email sign-up

**Comment by natalia-fitzgerald** [comment]
@meissadia @billhimmelsbach 
I captured everything noted here and we're moving to this other issue to continue with component tracking by page: https://github.com/cfpb/design-system-react/issues/224
